const WHITE = '#FFF';
const BLACK = '#000';

export const PRIMARY_COLOR= '#0095B9';
export const SECONDRY_COLOR = '#001C5D'
export const TERTIARY_COLOR ='#c5007e';

export const PRIMARY_BTN_COLOR = PRIMARY_COLOR;
export const SECONDRY_BTN_COLOR = SECONDRY_COLOR;
export const SCREEN_BACKGROUND_COLOR='#FCFCFC'
export const INPUT_FIELD_BGCOLOR= WHITE ;
export const INPUT_FIELD_BORDER_COLOR= SECONDRY_COLOR;
export const BTN_ACTIVE_GRADIENT_COLOR = [PRIMARY_COLOR, PRIMARY_COLOR];
export const SEC_BTN_ACTIVE_GRADIENT_COLOR = [WHITE, WHITE];
export const PRIMARY_BTN_DISABLED_COLOR = '#deefee';
export const TEXT_INPUT_TEXT_COLOR = SECONDRY_COLOR;
export const PRIMARY_TEXT_COLOR = PRIMARY_COLOR;
export const SECONDRY_TEXT_COLOR = SECONDRY_COLOR;
export const WHITE_BG = WHITE;
export const BOTTOM_LINE_COLOR='#05256c';
export const TEXT_INPUT_ICON_COLOR = '#66698D';
export const APP_BACKGROUND_COLOR='#FAFAFA'